./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 0
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 1
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 2
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 3
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 4
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 5
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 6
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 7
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 8
./rebalanceTest Experiments/steps/ BaseCorel/ Experiments/steps/features/ Experiments/steps/analysis/ 9